language: node_js
node_js:
  - '10'
  services:
  - postgresql
install: npm install
script: npm test
before_script:
  - psql -c 'create database mazus_ah_backend_test;' -U postgres
after_success: 
  - "npm run coveralls"
